In [1]:
import pandas as pd

In [2]:
#Load in tables of data itself and not the summary sheets
df = pd.read_excel('../data/landing/projections/VIF2023_projections.xlsx', sheet_name=['Component_Detail_Annual', '5yr_Age_Groups_Sex_2011_2051'], header=None)

In [3]:
population_changes = df['Component_Detail_Annual']
indv_changes = df['5yr_Age_Groups_Sex_2011_2051']

In [4]:
#Here we index to only grab the table data and it's content in the excel sheets
population_changes = population_changes[9:50]
#Rename each column to accruately represent the table data
population_changes.columns = ["Year", "Population at Start of Period", "Births", "Deaths", "Natural Increase", "Overseas Migration Arrivals", "Overseas Migration Departures", "Net Overseas Migration", "Interstate Migration Arrivals", "Interstate Migration Departures", "Net Interstate Migration", "Net Migration", "Population at End of Period", "Change in Population", "Annual Population Growth Rate", "Statistical Difference*"]

In [5]:
#We'll grab only useful columns
population_changes = population_changes[["Year", "Net Overseas Migration", "Net Interstate Migration", "Population at End of Period", "Change in Population"]]
population_changes

,Year,Net Overseas Migration,Net Interstate Migration,Population at End of Period,Change in Population
9,2011,NaN,NaN,5537817,NaN
10,2012,56174,2417,5651091,113274
11,2013,59034,6420,5772669,121578
12,2014,56906,9739,5894917,122248
13,2015,60694,11079,6022322,127405
14,2016,72215,17639,6173172,150850
15,2017,91243,13748,6302608,129436
16,2018,86968,9101,6423038,120430
17,2019,85476,6480,6537305,114267
18,2020,60597,-2652,6615046,77741
19,2021,-53059,-35622,6547822,-67224
20,2022,63993,-14865,6625964,78142
21,2023,146825.0,-4198.428159,6800630.016494,174748.016494
22,2024,117000.0,100.236156,6952766.338025,152136.321531
23,2025,69800,600.241062,7060161.820228,107395.482203
24,2026,82500,2100.241297,7181625.788554,121463.968326
25,2027,82580,3600.24574,7304715.773456,123089.984902
26,2028,82670.0,5100.253782,7429320.320246,124604.54679
27,2029,82750.0,5100.263738,7553747.908604,124427.588358
28,2030,82830.0,5100.275365,7678087.303445,124339.394841
29,2031,82910.0,5100.287475,7802503.019359,124415.715914
30,2032,82992.789379,5100.292757,7927018.927029,124515.90767
31,2033,83075.578759,5100.29399,8051678.588867,124659.661837
32,2034,83158.368138,5100.293153,8176540.034545,124861.445679
33,2035,83241.157517,5100.29073,8301665.756051,125125.721506
34,2036,83323.946896,5100.285178,8427079.190434,125413.434383
35,2037,83112.079276,5100.28235,8552696.203382,125617.012947
36,2038,82899.137655,5100.277874,8678573.30139,125877.098008
37,2039,82685.122034,5100.271028,8804717.754724,126144.453334
38,2040,82470.032413,5100.264108,8931109.343223,126391.5885
39,2041,82550.673793,5100.257381,9057947.784783,126838.441559
40,2042,82631.315172,5100.249856,9185141.213096,127193.428313
41,2043,82711.956551,5100.247128,9312585.835555,127444.622459
42,2044,82792.59793,5100.245679,9440168.785169,127582.949614
43,2045,82873.23931,5100.246474,9567755.253732,127586.468563
44,2046,82953.880689,5100.249655,9695238.83005,127483.576317
45,2047,83034.522068,5100.253049,9822516.854925,127278.024875
46,2048,83115.163447,5100.253487,9949488.751147,126971.896222
47,2049,83195.804827,5100.255965,10076121.524615,126632.773468
48,2050,83276.446206,5100.256708,10202395.403614,126273.879
49,2051,83357.087585,5100.256386,10328325.988055,125930.58444

In [6]:
#Rename columns to match the table data
indv_changes.columns = indv_changes.iloc[8]
#Makes sure we only read in data
indv_changes = indv_changes[9:]
#This just makes sure pandas displays numbers in full an integer format
pd.set_option("display.float_format", "{:.0f}".format)

In [7]:
#Here we change the dataframe columns so we have year and population as two seperate variables
indv_changes = indv_changes.melt(
    id_vars=["Sex", "Age", "5-year Age/Sex group", "15-year Age/Sex group"],
    var_name="Year",
    value_name="Population"
)

In [8]:
indv_changes

,Sex,Age,5-year Age/Sex group,15-year Age/Sex group,Year,Population
0,Males,0 to 4,Males - 0 to 4,Males - 0 to 14,2011,180813
1,Males,5 to 9,Males - 5 to 9,Males - 0 to 14,2011,170480
2,Males,10 to 14,Males - 10 to 14,Males - 0 to 14,2011,169404
3,Males,15 to 19,Males - 15 to 19,Males - 15 to 29,2011,181658
4,Males,20 to 24,Males - 20 to 24,Males - 15 to 29,2011,211018
...,...,...,...,...,...,...
2373,Persons,75 to 79,Persons - 75 to 79,Persons - 75 and over,2051,365301
2374,Persons,80 to 84,Persons - 80 to 84,Persons - 75 and over,2051,312742
2375,Persons,85 to 89,Persons - 85 to 89,Persons - 75 and over,2051,223741
2376,Persons,90 and over,Persons - 90 and over,Persons - 75 and over,2051,173444
2377,Persons,Total,Persons - Total,Persons - Total,2051,10328326

In [9]:
#Now we get the total popualtion for each 15 year age group
indv_changes = (
    indv_changes
    .groupby(["15-year Age/Sex group", "Year"], as_index=False)["Population"]
    .sum()
)

In [10]:
indv_changes

    15-year Age/Sex group Year  Population
0       Females - 0 to 14 2011      494039
1       Females - 0 to 14 2012      504330
2       Females - 0 to 14 2013      516192
3       Females - 0 to 14 2014      527555
4       Females - 0 to 14 2015      538712
..                    ...  ...         ...
774       Persons - Total 2047     9822517
775       Persons - Total 2048     9949489
776       Persons - Total 2049    10076122
777       Persons - Total 2050    10202395
778       Persons - Total 2051    10328326

[779 rows x 3 columns]

In [11]:
#We'll now make each 15-age groups it's own variable with it's corresponding year
indv_changes = indv_changes.pivot(
    index="Year",
    columns="15-year Age/Sex group",
    values="Population"
).reset_index()

In [ ]:
#We already have Total population from first dataframe
indv_changes = indv_changes.drop(columns=["Persons - Total"])

In [13]:
#Final merged data frame of both tables
population_data = pd.merge(population_changes, indv_changes, on="Year", how="left")

In [14]:
#We'll remove 2011 data due to missing values and limited relevance given it's age
population_data = population_data.drop(population_data.index[0])
population_data

,Year,Net Overseas Migration,Net Interstate Migration,Population at End of Period,Change in Population,Females - 0 to 14,Females - 15 to 29,Females - 30 to 44,Females - 45 to 59,Females - 60 to 74,...,Males - 30 to 44,Males - 45 to 59,Males - 60 to 74,Males - 75 and over,Persons - 0 to 14,Persons - 15 to 29,Persons - 30 to 44,Persons - 45 to 59,Persons - 60 to 74,Persons - 75 and over
1,2012,56174,2417,5651091,113274,504330,594739,611612,551808,376650,...,600841,533198,360042,155779,1035904,1209620,1212453,1085006,736692,371416
2,2013,59034,6420,5772669,121578,516192,605220,623533,561278,390237,...,613988,541284,372187,161017,1060155,1229200,1237521,1102562,762424,380807
3,2014,56906,9739,5894917,122248,527555,617404,634535,572255,403419,...,624196,550136,383494,166488,1083457,1252465,1258731,1122391,786913,390960
4,2015,60694,11079,6022322,127405,538712,630121,647200,582989,416966,...,635941,558550,395122,172040,1107752,1276628,1283141,1141539,812088,401174
5,2016,72215,17639,6173172,150850,554284,645158,660095,596288,431794,...,649650,567885,408044,178048,1140064,1306807,1309745,1164173,839838,412545
6,2017,91243,13748,6302608,129436,564594,656880,674186,605943,444968,...,664220,577355,418150,183931,1161960,1332362,1338406,1183298,863118,423464
7,2018,86968,9101,6423038,120430,572918,665905,690961,612136,458708,...,680131,584133,428401,189492,1179414,1355475,1371092,1196269,887109,433679
8,2019,85476,6480,6537305,114267,580345,671350,707938,618196,472181,...,696148,589698,438973,195966,1193892,1373549,1404086,1207894,911154,446730
9,2020,60597,-2652,6615046,77741,583911,659128,723989,624323,491459,...,711262,595353,452955,203877,1200620,1352646,1435251,1219676,944414,462439
10,2021,-53059,-35622,6547822,-67224,580276,622387,724905,618425,498387,...,709637,593036,457591,211640,1192206,1276147,1434542,1211461,955978,477488
11,2022,63993,-14865,6625964,78142,580787,631718,738475,618216,503321,...,722807,592676,461335,222750,1192342,1296605,1461282,1210892,964656,500105
12,2023,146825,-4198,6800630,174748,589112,661413,762786,622835,512567,...,747022,597050,469389,232846,1208917,1358388,1509807,1219884,981956,521677
13,2024,117000,100,6952766,152136,596188,683535,783933,628546,521781,...,769752,602659,477432,242129,1222949,1403593,1553685,1231205,999213,542121
14,2025,69800,600,7060162,107395,600023,695353,798536,634312,528359,...,786087,608056,483521,251688,1231192,1426421,1584623,1242368,1011880,563677
15,2026,82500,2100,7181626,121464,605594,709963,812346,643363,534804,...,801895,617040,489391,261181,1242494,1455114,1614241,1260402,1024196,585179
16,2027,82580,3600,7304716,123090,610701,725970,824521,654249,541270,...,816004,628026,495144,270375,1252883,1486528,1640525,1282276,1036414,606090
17,2028,82670,5100,7429320,124605,615573,742790,835261,665965,548139,...,827998,639962,501725,279576,1262615,1520224,1663259,1305927,1049865,627431
18,2029,82750,5100,7553748,124428,621015,758204,846536,676398,556708,...,840474,651162,509583,288385,1273314,1551354,1687010,1327560,1066290,648220
19,2030,82830,5100,7678087,124339,626576,772159,857929,688250,564681,...,853907,663040,517130,297429,1284630,1578884,1711836,1351290,1081812,669635
20,2031,82910,5100,7802503,124416,632016,785944,869369,697878,575144,...,867753,673594,525764,306916,1295491,1605966,1737123,1371473,1100909,691542
21,2032,82993,5100,7927019,124516,638685,798818,880608,708756,584142,...,880411,685107,533893,316020,1309125,1631762,1761019,1393863,1118035,713216
22,2033,83076,5100,8051679,124660,646417,810477,891184,722980,590498,...,892959,698398,540228,325193,1324830,1655479,1784143,1421378,1130726,735122
23,2034,83158,5100,8176540,124861,654585,821941,901346,738292,595898,...,905221,713077,545025,334856,1341923,1678129,1806568,1451369,1140923,757629
24,2035,83241,5100,8301666,125126,664002,831870,910684,755968,600094,...,917486,729179,549503,344108,1361298,1697697,1828170,1485147,1149597,779757
25,2036,83324,5100,8427079,125413,672841,840275,922300,774838,602733,...,931479,746210,552743,354018,1380056,1713915,1853779,1521048,1155476,802805
26,2037,83112,5100,8552696,125617,682862,845395,936868,792970,605718,...,948623,763385,555359,363880,1400699,1723708,1885491,1556355,1161077,825366
27,2038,82899,5100,8678573,125877,692494,850416,952028,811007,608994,...,965654,781014,558415,373538,1420492,1733516,1917682,1592021,1167408,847453
28,2039,82685,5100,8804718,126144,701871,855818,967296,828075,613920,...,981789,798990,563071,382254,1439754,1744117,1949085,1627065,1176991,867705
29,2040,82470,5100,8931109,126392,711171,860639,983114,844630,620832,...,997098,817177,569494,390044,1458857,1754237,1980212,1661807,1190326,885671
30,2041,82551,5100,9057948,126838,720795,866355,998711,858603,630210,...,1012316,832825,578561,397224,1478628,1765825,2011027,1691428,1208771,902270
31,2042,82631,5100,9185141,127193,730629,871552,1015309,870891,641176,...,1028437,846694,589361,404029,1498828,1776463,2043746,1717585,1230537,917983
32,2043,82712,5100,9312586,127445,740656,876535,1032344,881548,652919,...,1045497,858507,601080,411475,1519424,1786454,2077842,1740055,1253999,934813
33,2044,82793,5100,9440169,127583,750869,882072,1048126,892590,663537,...,1061399,870786,612157,419751,1540401,1797450,2109526,1763376,1275694,953722
34,2045,82873,5100,9567755,127586,761127,887918,1062390,903731,675395,...,1075235,884023,623802,428068,1561470,1809273,2137625,1787754,1299197,972436
35,2046,82954,5100,9695239,127484,771262,893614,1076574,914875,685212,...,1088835,897549,634317,437845,1582287,1820689,2165409,1812424,1319529,994901
36,2047,83035,5100,9822517,127278,781184,900716,1089696,925783,696147,...,1101980,909972,645612,446965,1602666,1835111,2191676,1835754,1341759,1015551
37,2048,83115,5100,9949489,126972,790803,909003,1101473,936133,710094,...,1114149,922286,658441,454715,1622423,1851843,2215622,1858418,1368535,1032648
38,2049,83196,5100,10076122,126633,800037,917831,1112877,946133,725140,...,1125472,934356,672572,461678,1641389,1869957,2238349,1880489,1397712,1048225
39,2050,83276,5100,10202395,126274,808824,927885,1122673,955489,742370,...,1135008,946519,688041,468142,1659441,1890471,2257681,1902007,1430412,1062384
40,2051,83357,5100,10328326,125931,817153,937465,1130895,967023,760699,...,1142773,960436,704306,474257,1676549,1910417,2273668,1927459,1465005,1075228

In [15]:
# create the processed data directory if it doesn't exist
import os
os.makedirs('../data/processed/population', exist_ok=True)

# Save the processed school location data to a new CSV file
population_data.to_csv('../data/processed/population/population_data.csv', index=False)