In [60]:
import pandas as pd
import numpy as np

In [61]:
#Load in tables of data itself and not the summary sheets
df = pd.read_excel('../data/landing/projections/VIF2023_projections.xlsx', sheet_name=['Component_Detail_Annual', '5yr_Age_Groups_Sex_2011_2051'], header=None)

In [62]:
population_changes = df['Component_Detail_Annual']
indv_changes = df['5yr_Age_Groups_Sex_2011_2051']

In [63]:
#Here we index to only grab the table data and it's content in the excel sheets
population_changes = population_changes[9:50]
#Rename each column to accruately represent the table data
population_changes.columns = ["Year", "Population at Start of Period", "Births", "Deaths", "Natural Increase", "Overseas Migration Arrivals", "Overseas Migration Departures", "Net Overseas Migration", "Interstate Migration Arrivals", "Interstate Migration Departures", "Net Interstate Migration", "Net Migration", "Population at End of Period", "Change in Population", "Annual Population Growth Rate", "Statistical Difference*"]

In [64]:
#We'll grab only useful columns
population_changes = population_changes[["Year", "Net Overseas Migration", "Net Interstate Migration", "Population at End of Period", "Change in Population"]]
population_changes

,Year,Net Overseas Migration,Net Interstate Migration,Population at End of Period,Change in Population
9,2011,NaN,NaN,5537817,NaN
10,2012,56174,2417,5651091,113274
11,2013,59034,6420,5772669,121578
12,2014,56906,9739,5894917,122248
13,2015,60694,11079,6022322,127405
14,2016,72215,17639,6173172,150850
15,2017,91243,13748,6302608,129436
16,2018,86968,9101,6423038,120430
17,2019,85476,6480,6537305,114267
18,2020,60597,-2652,6615046,77741
19,2021,-53059,-35622,6547822,-67224
20,2022,63993,-14865,6625964,78142
21,2023,146825.0,-4198.428159,6800630.016494,174748.016494
22,2024,117000.0,100.236156,6952766.338025,152136.321531
23,2025,69800,600.241062,7060161.820228,107395.482203
24,2026,82500,2100.241297,7181625.788554,121463.968326
25,2027,82580,3600.24574,7304715.773456,123089.984902
26,2028,82670.0,5100.253782,7429320.320246,124604.54679
27,2029,82750.0,5100.263738,7553747.908604,124427.588358
28,2030,82830.0,5100.275365,7678087.303445,124339.394841
29,2031,82910.0,5100.287475,7802503.019359,124415.715914
30,2032,82992.789379,5100.292757,7927018.927029,124515.90767
31,2033,83075.578759,5100.29399,8051678.588867,124659.661837
32,2034,83158.368138,5100.293153,8176540.034545,124861.445679
33,2035,83241.157517,5100.29073,8301665.756051,125125.721506
34,2036,83323.946896,5100.285178,8427079.190434,125413.434383
35,2037,83112.079276,5100.28235,8552696.203382,125617.012947
36,2038,82899.137655,5100.277874,8678573.30139,125877.098008
37,2039,82685.122034,5100.271028,8804717.754724,126144.453334
38,2040,82470.032413,5100.264108,8931109.343223,126391.5885
39,2041,82550.673793,5100.257381,9057947.784783,126838.441559
40,2042,82631.315172,5100.249856,9185141.213096,127193.428313
41,2043,82711.956551,5100.247128,9312585.835555,127444.622459
42,2044,82792.59793,5100.245679,9440168.785169,127582.949614
43,2045,82873.23931,5100.246474,9567755.253732,127586.468563
44,2046,82953.880689,5100.249655,9695238.83005,127483.576317
45,2047,83034.522068,5100.253049,9822516.854925,127278.024875
46,2048,83115.163447,5100.253487,9949488.751147,126971.896222
47,2049,83195.804827,5100.255965,10076121.524615,126632.773468
48,2050,83276.446206,5100.256708,10202395.403614,126273.879
49,2051,83357.087585,5100.256386,10328325.988055,125930.58444

In [65]:
#Rename columns to match the table data
indv_changes.columns = indv_changes.iloc[8]
#Makes sure we only read in data
indv_changes = indv_changes[9:]

In [66]:
#Here we change the dataframe columns so we have year and population as two seperate variables
indv_changes = indv_changes.melt(
    id_vars=["Sex", "Age", "5-year Age/Sex group", "15-year Age/Sex group"],
    var_name="Year",
    value_name="Population"
)

In [67]:
indv_changes

,Sex,Age,5-year Age/Sex group,15-year Age/Sex group,Year,Population
0,Males,0 to 4,Males - 0 to 4,Males - 0 to 14,2011.0,1.808130e+05
1,Males,5 to 9,Males - 5 to 9,Males - 0 to 14,2011.0,1.704800e+05
2,Males,10 to 14,Males - 10 to 14,Males - 0 to 14,2011.0,1.694040e+05
3,Males,15 to 19,Males - 15 to 19,Males - 15 to 29,2011.0,1.816580e+05
4,Males,20 to 24,Males - 20 to 24,Males - 15 to 29,2011.0,2.110180e+05
...,...,...,...,...,...,...
2373,Persons,75 to 79,Persons - 75 to 79,Persons - 75 and over,2051.0,3.653008e+05
2374,Persons,80 to 84,Persons - 80 to 84,Persons - 75 and over,2051.0,3.127423e+05
2375,Persons,85 to 89,Persons - 85 to 89,Persons - 75 and over,2051.0,2.237413e+05
2376,Persons,90 and over,Persons - 90 and over,Persons - 75 and over,2051.0,1.734436e+05
2377,Persons,Total,Persons - Total,Persons - Total,2051.0,1.032833e+07

In [68]:
#Now we get the total popualtion for each 15 year age group
indv_changes = (
    indv_changes
    .groupby(["15-year Age/Sex group", "Year"], as_index=False)["Population"]
    .sum()
)

In [69]:
indv_changes

    15-year Age/Sex group    Year    Population
0       Females - 0 to 14  2011.0  4.940390e+05
1       Females - 0 to 14  2012.0  5.043300e+05
2       Females - 0 to 14  2013.0  5.161920e+05
3       Females - 0 to 14  2014.0  5.275550e+05
4       Females - 0 to 14  2015.0  5.387120e+05
..                    ...     ...           ...
774       Persons - Total  2047.0  9.822517e+06
775       Persons - Total  2048.0  9.949489e+06
776       Persons - Total  2049.0  1.007612e+07
777       Persons - Total  2050.0  1.020240e+07
778       Persons - Total  2051.0  1.032833e+07

[779 rows x 3 columns]

In [70]:
#We'll now make each 15-age groups it's own variable with it's corresponding year
indv_changes = indv_changes.pivot(
    index="Year",
    columns="15-year Age/Sex group",
    values="Population"
).reset_index()

In [71]:
#We already have Total population from first dataframe
indv_changes = indv_changes.drop(columns=["Persons - Total"])

In [72]:
#Final merged data frame of both tables
population_data = pd.merge(population_changes, indv_changes, on="Year", how="left")

In [73]:
#We'll remove 2011 data due to missing values and limited relevance given it's age
population_data = population_data.drop(population_data.index[0])
#Round all numbers down
population_data = np.floor(population_data).astype(int)

In [74]:
# List columns for females, males, and persons
female_cols = [col for col in population_data.columns if col.startswith("Females")]
male_cols = [col for col in population_data.columns if col.startswith("Males")]
person_cols = [col for col in population_data.columns if col.startswith("Persons")]

# Convert to percentages of total population
population_data[female_cols] = population_data[female_cols].div(population_data["Population at End of Period"], axis=0) 
population_data[male_cols] = population_data[male_cols].div(population_data["Population at End of Period"], axis=0) 
population_data[person_cols] = population_data[person_cols].div(population_data["Population at End of Period"], axis=0) 

# Round to 2 decimals
population_data[female_cols + male_cols + person_cols] = population_data[female_cols + male_cols + person_cols].round(2)

In [75]:
#Rename columns
population_data.rename(columns={'Population at End of Period': 'Population'}, inplace=True)

#This code was made with assitance of Chat GPT to efficeint rename columns
population_data.rename(columns=lambda x: f'Percentage - {x}' if x.startswith(('Females', 'Males', 'Persons')) else x, inplace=True)

In [76]:
population_data

,Year,Net Overseas Migration,Net Interstate Migration,Population,Change in Population,Percentage - Females - 0 to 14,Percentage - Females - 15 to 29,Percentage - Females - 30 to 44,Percentage - Females - 45 to 59,Percentage - Females - 60 to 74,...,Percentage - Males - 30 to 44,Percentage - Males - 45 to 59,Percentage - Males - 60 to 74,Percentage - Males - 75 and over,Percentage - Persons - 0 to 14,Percentage - Persons - 15 to 29,Percentage - Persons - 30 to 44,Percentage - Persons - 45 to 59,Percentage - Persons - 60 to 74,Percentage - Persons - 75 and over
1,2012,56174,2417,5651091,113274,0.09,0.11,0.11,0.10,0.07,...,0.11,0.09,0.06,0.03,0.18,0.21,0.21,0.19,0.13,0.07
2,2013,59034,6420,5772669,121578,0.09,0.10,0.11,0.10,0.07,...,0.11,0.09,0.06,0.03,0.18,0.21,0.21,0.19,0.13,0.07
3,2014,56906,9739,5894917,122248,0.09,0.10,0.11,0.10,0.07,...,0.11,0.09,0.07,0.03,0.18,0.21,0.21,0.19,0.13,0.07
4,2015,60694,11079,6022322,127405,0.09,0.10,0.11,0.10,0.07,...,0.11,0.09,0.07,0.03,0.18,0.21,0.21,0.19,0.13,0.07
5,2016,72215,17639,6173172,150850,0.09,0.10,0.11,0.10,0.07,...,0.11,0.09,0.07,0.03,0.18,0.21,0.21,0.19,0.14,0.07
6,2017,91243,13748,6302608,129436,0.09,0.10,0.11,0.10,0.07,...,0.11,0.09,0.07,0.03,0.18,0.21,0.21,0.19,0.14,0.07
7,2018,86968,9101,6423038,120430,0.09,0.10,0.11,0.10,0.07,...,0.11,0.09,0.07,0.03,0.18,0.21,0.21,0.19,0.14,0.07
8,2019,85476,6480,6537305,114267,0.09,0.10,0.11,0.09,0.07,...,0.11,0.09,0.07,0.03,0.18,0.21,0.21,0.18,0.14,0.07
9,2020,60597,-2652,6615046,77741,0.09,0.10,0.11,0.09,0.07,...,0.11,0.09,0.07,0.03,0.18,0.20,0.22,0.18,0.14,0.07
10,2021,-53059,-35622,6547822,-67224,0.09,0.10,0.11,0.09,0.08,...,0.11,0.09,0.07,0.03,0.18,0.19,0.22,0.19,0.15,0.07
11,2022,63993,-14865,6625964,78142,0.09,0.10,0.11,0.09,0.08,...,0.11,0.09,0.07,0.03,0.18,0.20,0.22,0.18,0.15,0.08
12,2023,146824,-4199,6800630,174748,0.09,0.10,0.11,0.09,0.08,...,0.11,0.09,0.07,0.03,0.18,0.20,0.22,0.18,0.14,0.08
13,2024,116999,100,6952766,152136,0.09,0.10,0.11,0.09,0.08,...,0.11,0.09,0.07,0.03,0.18,0.20,0.22,0.18,0.14,0.08
14,2025,69800,600,7060161,107395,0.08,0.10,0.11,0.09,0.07,...,0.11,0.09,0.07,0.04,0.17,0.20,0.22,0.18,0.14,0.08
15,2026,82500,2100,7181625,121463,0.08,0.10,0.11,0.09,0.07,...,0.11,0.09,0.07,0.04,0.17,0.20,0.22,0.18,0.14,0.08
16,2027,82580,3600,7304715,123089,0.08,0.10,0.11,0.09,0.07,...,0.11,0.09,0.07,0.04,0.17,0.20,0.22,0.18,0.14,0.08
17,2028,82670,5100,7429320,124604,0.08,0.10,0.11,0.09,0.07,...,0.11,0.09,0.07,0.04,0.17,0.20,0.22,0.18,0.14,0.08
18,2029,82750,5100,7553747,124427,0.08,0.10,0.11,0.09,0.07,...,0.11,0.09,0.07,0.04,0.17,0.21,0.22,0.18,0.14,0.09
19,2030,82830,5100,7678087,124339,0.08,0.10,0.11,0.09,0.07,...,0.11,0.09,0.07,0.04,0.17,0.21,0.22,0.18,0.14,0.09
20,2031,82910,5100,7802503,124415,0.08,0.10,0.11,0.09,0.07,...,0.11,0.09,0.07,0.04,0.17,0.21,0.22,0.18,0.14,0.09
21,2032,82992,5100,7927018,124515,0.08,0.10,0.11,0.09,0.07,...,0.11,0.09,0.07,0.04,0.17,0.21,0.22,0.18,0.14,0.09
22,2033,83075,5100,8051678,124659,0.08,0.10,0.11,0.09,0.07,...,0.11,0.09,0.07,0.04,0.16,0.21,0.22,0.18,0.14,0.09
23,2034,83158,5100,8176540,124861,0.08,0.10,0.11,0.09,0.07,...,0.11,0.09,0.07,0.04,0.16,0.21,0.22,0.18,0.14,0.09
24,2035,83241,5100,8301665,125125,0.08,0.10,0.11,0.09,0.07,...,0.11,0.09,0.07,0.04,0.16,0.20,0.22,0.18,0.14,0.09
25,2036,83323,5100,8427079,125413,0.08,0.10,0.11,0.09,0.07,...,0.11,0.09,0.07,0.04,0.16,0.20,0.22,0.18,0.14,0.10
26,2037,83112,5100,8552696,125617,0.08,0.10,0.11,0.09,0.07,...,0.11,0.09,0.06,0.04,0.16,0.20,0.22,0.18,0.14,0.10
27,2038,82899,5100,8678573,125877,0.08,0.10,0.11,0.09,0.07,...,0.11,0.09,0.06,0.04,0.16,0.20,0.22,0.18,0.13,0.10
28,2039,82685,5100,8804717,126144,0.08,0.10,0.11,0.09,0.07,...,0.11,0.09,0.06,0.04,0.16,0.20,0.22,0.18,0.13,0.10
29,2040,82470,5100,8931109,126391,0.08,0.10,0.11,0.09,0.07,...,0.11,0.09,0.06,0.04,0.16,0.20,0.22,0.19,0.13,0.10
30,2041,82550,5100,9057947,126838,0.08,0.10,0.11,0.09,0.07,...,0.11,0.09,0.06,0.04,0.16,0.19,0.22,0.19,0.13,0.10
31,2042,82631,5100,9185141,127193,0.08,0.09,0.11,0.09,0.07,...,0.11,0.09,0.06,0.04,0.16,0.19,0.22,0.19,0.13,0.10
32,2043,82711,5100,9312585,127444,0.08,0.09,0.11,0.09,0.07,...,0.11,0.09,0.06,0.04,0.16,0.19,0.22,0.19,0.13,0.10
33,2044,82792,5100,9440168,127582,0.08,0.09,0.11,0.09,0.07,...,0.11,0.09,0.06,0.04,0.16,0.19,0.22,0.19,0.14,0.10
34,2045,82873,5100,9567755,127586,0.08,0.09,0.11,0.09,0.07,...,0.11,0.09,0.07,0.04,0.16,0.19,0.22,0.19,0.14,0.10
35,2046,82953,5100,9695238,127483,0.08,0.09,0.11,0.09,0.07,...,0.11,0.09,0.07,0.05,0.16,0.19,0.22,0.19,0.14,0.10
36,2047,83034,5100,9822516,127278,0.08,0.09,0.11,0.09,0.07,...,0.11,0.09,0.07,0.05,0.16,0.19,0.22,0.19,0.14,0.10
37,2048,83115,5100,9949488,126971,0.08,0.09,0.11,0.09,0.07,...,0.11,0.09,0.07,0.05,0.16,0.19,0.22,0.19,0.14,0.10
38,2049,83195,5100,10076121,126632,0.08,0.09,0.11,0.09,0.07,...,0.11,0.09,0.07,0.05,0.16,0.19,0.22,0.19,0.14,0.10
39,2050,83276,5100,10202395,126273,0.08,0.09,0.11,0.09,0.07,...,0.11,0.09,0.07,0.05,0.16,0.19,0.22,0.19,0.14,0.10
40,2051,83357,5100,10328325,125930,0.08,0.09,0.11,0.09,0.07,...,0.11,0.09,0.07,0.05,0.16,0.18,0.22,0.19,0.14,0.10

In [ ]:
# create the processed data directory if it doesn't exist
import os
os.makedirs('../data/processed/population', exist_ok=True)

# Save the processed school location data to a new CSV file
population_data.to_csv('../data/processed/population/population_data.csv', index=False)